"""empty message

Revision ID: dea30ed75b2f
Revises: dcfc360d7034
Create Date: 2025-02-04 23:08:04.506168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea30ed75b2f'
down_revision = 'dcfc360d7034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('characters', sa.Integer(), nullable=True))
        batch_op.drop_constraint('character_charachters_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'character', ['characters'], ['id'])
        batch_op.drop_column('charachters')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charachters', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('character_charachters_fkey', 'character', ['charachters'], ['id'])
        batch_op.drop_column('characters')

    # ### end Alembic commands ###
